In [1]:
#contents:
#Different methods in numpy to create array
#converting list,tupple,string to array
#arrange function
#Array attribute shape,ndimen,itemsize,reshape()
#indexing and slicing operation of array

In [3]:
#Different methods in numpy to create array

import numpy as np

A= np.array([[1,2,3],[4,5,6]])     #using function array()
B= np.empty([2,3])         #using function empty()
C= np.zeros([3,3])         #zeros()
D=np.ones([4,4])           #ones()

print(A)
print(B)
print(C)
print(D)

[[1 2 3]
 [4 5 6]]
[[1.11260348e-306 1.44635488e-307 9.34609111e-307]
 [5.11798224e-307 8.90071136e-308 1.42419938e-306]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
#converting list,tupple,string to array
L=[1,2,3,4]
T= (1,2,3,4)
S= "HELLO"

A= np.asarray(L)
print(A)
A= np.asarray(T)
print(A)
A= np.asarray(S)
print(A)

[1 2 3 4]
[1 2 3 4]
HELLO


In [9]:
#arrange function
A=np.arange(10)
print(A)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
A=np.array([[1,2,3],[4,5,6]])
print(A.shape)
print(A.ndim)
print(A.itemsize)
print(A.reshape(3,2))

(2, 3)
2
4
[[1 2]
 [3 4]
 [5 6]]


In [26]:
B= A[0,:]
C= A[1,:]

sum=0
for i in B:
    sum+=i
    
print(sum)


6
