In [4]:
#Numpy and pandas tutorial

import numpy as np

a= np.array([1,2,3,4,5])
b=np.array([[1,2,3],[4,5,6]])
print(a.shape) # to see dimention of saay shape is used
print(b.shape)

print(a)
print(b)

(5,)
(2, 3)
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [5]:
print(b[0,0]) #accessing first element of array

1


In [9]:
#Create 2d array and find the sum of all element
b=np.array([[3,8,1],[7,3,5]])
s=0
for x in b:
    for y in x:
        s+=y
        
print(s)

27


In [14]:
#to find sum of each row and column

b=np.array([[1,2,3],[4,5,6],[7,8,9]])

r,c=b.shape

for i in range (0,r): # sum of rows
    rsum=0
    for j in range(0,c):
       rsum+=b[i,j]
    print("Sum of ",i+1,"th row is: ",rsum)
    

for i in range (0,r): #sum of columns
    rsum=0
    for j in range (0,c):
        rsum+=b[j,i]
    print("Sum of ",i+1,"th column is: ",rsum)
    

print()
print()

b=np.array([[1,2],[3,4],[5,6]])

r,c=b.shape

for i in range (0,r): # sum of rows
    rsum=0
    for j in range(0,c):
       rsum+=b[i,j]
    print("Sum of ",i+1,"th row is: ",rsum)
    

for i in range (0,c): #sum of columns
    rsum=0
    for j in range (0,r):
        rsum+=b[j,i]
    print("Sum of ",i+1,"th column is: ",rsum)

Sum of  1 th row is:  6
Sum of  2 th row is:  15
Sum of  3 th row is:  24
Sum of  1 th column is:  12
Sum of  2 th column is:  15
Sum of  3 th column is:  18


Sum of  1 th row is:  3
Sum of  2 th row is:  7
Sum of  3 th row is:  11
Sum of  1 th column is:  9
Sum of  2 th column is:  12


In [23]:
# using sum function printing sum,sum of rows,sum of column

b=np.array([[1,2,3],[4,5,6]])
sum=np.sum(b)
rsum=np.sum(b,axis=1)   #to get row sum
csum=np.sum(b,axis=0)   #to get column sum
print(sum)
print(rsum)
print(csum)

21
[ 6 15]
[5 7 9]


In [19]:
#methods to add substract multiply divide, sum std average

b1=np.array([[1,2,3],[4,5,6]])
b2=np.array([[7,8,9],[10,11,12]])

b3=np.add(b1,b2)   #for adding
print(b3)

b3=np.subtract(b2,b1)   #for subtracting
print(b3)

[[ 8 10 12]
 [14 16 18]]
[[6 6 6]
 [6 6 6]]


In [28]:
#to find number of all the zero in array (sparse matrix)

b=np.array([[1,2,3,0,0],[0,0,4,5,6],[0,0,0,1,1],[2,3,4,5,0]])

count=0

for x in b:
    for y in x:
        if(y==0):
            count+=1  #increment operator is not suported in python
            
print(count)

8
