In [1]:
#K cluster

In [3]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn.datasets import load_digits

In [17]:
digits=load_digits()
kmeans=KMeans(n_clusters=10, random_state=0)
clusters= kmeans.fit_predict(digits.data)
print(kmeans.cluster_centers_.shape)
print(kmeans.cluster_centers_)

(10, 64)
[[ 0.00000000e+00  1.66533454e-16  3.07228916e-01  7.16265060e+00
   1.19457831e+01  1.93373494e+00  1.50602410e-01  5.42168675e-02
   1.73472348e-18  1.20481928e-02  3.28313253e+00  1.37951807e+01
   8.46385542e+00  1.53012048e+00  9.75903614e-01  2.77108434e-01
   8.67361738e-19  6.44578313e-01  1.07108434e+01  1.15602410e+01
   4.33734940e+00  5.25903614e+00  3.87349398e+00  3.25301205e-01
   6.02409639e-03  4.75903614e+00  1.47590361e+01  5.86144578e+00
   6.87951807e+00  1.07530120e+01  6.21686747e+00  1.80722892e-02
   0.00000000e+00  8.92771084e+00  1.48072289e+01  9.35542169e+00
   1.28132530e+01  1.43915663e+01  5.48192771e+00  0.00000000e+00
   9.63855422e-02  6.50602410e+00  1.16867470e+01  1.23433735e+01
   1.48373494e+01  1.07590361e+01  1.56626506e+00  1.38777878e-17
   6.02409639e-02  1.11445783e+00  3.00000000e+00  7.77710843e+00
   1.40843373e+01  4.13253012e+00  1.80722892e-02  0.00000000e+00
   1.08420217e-19  2.40963855e-02  3.73493976e-01  7.96385542e+00
 

In [19]:
#By creating our own data

import numpy as np
from sklearn.cluster import KMeans
#from sklearn.datasets import load_digits

Features= np.array([[2,2,167],[2,2,158],[2,2,150],[2,4,30],[2,4,15],[2,4,23],[2,2,4],[2,2,3],[2,2,1]])    #features for man's, dog's, bird's eyes,leg and height respectively
kmeans=KMeans(n_clusters=3, random_state=0)
clusters= kmeans.fit_predict(Features)
print(kmeans.cluster_centers_.shape)
print(kmeans.cluster_centers_)

(3, 3)
[[  2.           4.          22.66666667]
 [  2.           2.         158.33333333]
 [  2.           2.           2.66666667]]
